sudo: required

services:
  - docker

before_install:
  - docker pull obolibrary/odkfull

# command to run tests
script: cd src/ontology && sh run.sh make test

#after_success:
#  coveralls

# whitelist
branches:
  only:
    - master
    - test-travis

before_script:
  - mkdir -p bin
  - export PATH=$PATH:$PWD/bin
  - wget http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/software/utilities/check-obo-for-standard-release.pl -O bin/check-obo-for-standard-release.pl
  - chmod +x bin/*

# command to run tests
script: ./run.sh make travis_test

#after_success:
#  coveralls

# whitelist
branches:
  only:
    - master

notifications:
  email:
    - cjmungall@lbl.gov

