site_name: Uberon multi-species anatomy ontology
theme: readthedocs
nav:
  - Getting started: index.md
  - About Uberon: about.md
  - Cite: cite.md
  - Uberon on GitHub: https://github.com/obophenotype/uberon
  - Issue Tracker: https://github.com/obophenotype/uberon
  - Documentation:
      - Wiki: https://github.com/obophenotype/uberon/wiki
      - Uberon Manual: https://github.com/obophenotype/uberon/wiki/Manual
      - User Documentation: https://github.com/obophenotype/uberon/wiki/Manual#user-docs
      - Editors documentation: https://github.com/obophenotype/uberon/wiki/Manual#editor-docs
      - Design Patterns: https://github.com/obophenotype/uberon/wiki/Manual#design-patterns
      - Anatomical Structures: https://github.com/obophenotype/uberon/wiki/Manual#anatomical-structures
  - Browse:
      - OLS: https://www.ebi.ac.uk/ols/ontologies/uberon
      - Ontobee: http://www.ontobee.org/ontology/UBERON
      - BioPortal: https://bioportal.bioontology.org/ontologies/UBERON
  - Download:
      - Current release: current_release.md
      - Cross-species bridge files: bridges.md
      - Combined Multispecies Ontologies: combined_multispecies.md
      - Releases before 2020: old_releases.md
  - Acknowledgements: acknowledgements.md
  - Adopters: adopters.md
  - How-to guides:
      - Standard ODK workflows:
          - Overview: odk-workflows/index.md
          - Editors Workflow: odk-workflows/EditorsWorkflow.md
          - Release Workflow: odk-workflows/ReleaseWorkflow.md
          - Manage your ODK Repository: odk-workflows/RepoManagement.md
          - Setting up Docker for ODK: odk-workflows/SettingUpDockerForODK.md
          - Imports management: odk-workflows/UpdateImports.md
          - Managing the documentation: odk-workflows/ManageDocumentation.md
          - Continuous Integration: odk-workflows/ContinuousIntegration.md
          - Your ODK Repository Overview: odk-workflows/RepositoryFileStructure.md 
      - Contributing: contributing.md
  - Reference:
     Uberon Build Pipeline: uberon_build_pipeline.md

