# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "ontology_qc"
  ontology_qc:
    # The type of runner that the job will run on
    runs-on: macos-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: docker-practice/actions-setup-docker@master
      - run: |
          set -x
          docker version
      - name: Install ODK
        run: docker pull obolibrary/odkfull:v1.4.3
      # Checks-out current branch
      - uses: actions/checkout@v3
      - name: Run ontology QC checks
        run: |
          cd src/ontology
          mkdir -p tmp reports mirror
          docker run -v $PWD/../../:/work -w /work/src/ontology -e ROBOT_JAVA_ARGS='-Xmx9G' -e JAVA_OPTS='-Xmx9G' --rm obolibrary/odkfull:v1.4.3 make BRI=false MIR=false IMP=false test > TESTLOG.log
        env:
          DEFAULT_BRANCH: master
      - name: Last rows of QC report
        if: ${{ failure() }}
        run: tail -20 src/ontology/TESTLOG.log
